# /// script
# requires-python = ">=3.11"
# dependencies = ["marimo>=0.23.8", "numpy>=2.0"]
# ///

import marimo

__generated_with = "0.23.14"
app = marimo.App(width="full")


@app.cell
def _():
    import sys
    from pathlib import Path
    import marimo as mo

    here = (Path(__file__).resolve().parents[1] / "proved_matrix_groups/packages/barnes_wall_lattice_automorphism_groups/real_clifford/notebook.py").parent
    if str(here) not in sys.path:
        sys.path.insert(0, str(here))
    from verification import run_sweep
    return mo, run_sweep


@app.cell
def _(mo):
    mo.md(r"""
    # Barnes--Wall family II: real Clifford normalizers

    The matrix groups generated by real Pauli matrices, tensor Hadamards,
    and CNOT have orders \(16\) and \(2304\) in dimensions \(2\) and \(4\).
    The notebook partitions each group into \(E_m\)-cosets, evaluates the
    coset functions \(\Phi_m\), and compares their average with a direct
    average over all Clifford matrices.

    It also changes every coset lift to test the claimed lift independence,
    checks the normalizer action on \(E_m\), and records the one-row values
    \(0,1,1,1,2\) in degrees \(1,2,4,6,8\). Only entries satisfying
    \(m\geq k-1\) are labeled as consequences of the stable code theorem.
    Every matrix is checked to be real orthogonal before the averages run.
    """)
    return


@app.cell
def _(mo):
    run = mo.ui.run_button(label="Close C_m and check formulas (11.7)--(11.13)")
    run
    return (run,)


@app.cell
def _(mo, run, run_sweep):
    mo.stop(not run.value, mo.md("Press the button to close the groups and average their cosets."))
    rows = run_sweep()
    passed = all(row["passed"] for row in rows)
    mo.vstack([
        mo.callout(
            f"{'All' if passed else 'Not all'} {len(rows)} Clifford checks passed.",
            kind="success" if passed else "danger",
        ),
        mo.ui.table(rows, pagination=True),
    ])
    return


if __name__ == "__main__":
    app.run()
