"""Exact verification for the natural and deleted M11 representations.

The direct route enumerates the group generated by the ATLAS permutations,
constructs every matrix, and obtains complete symmetric characters from
matrix traces.  The formula route uses only the independently entered
class-size/cycle-shape table.  A third route traverses configuration orbits
under the two generators for representative permutation coefficients.
"""

from __future__ import annotations

from collections import Counter, deque
from functools import lru_cache
from itertools import combinations_with_replacement, product
from math import comb, prod
from typing import Iterable, Sequence

import numpy as np


Permutation = tuple[int, ...]
CycleShape = tuple[tuple[int, int], ...]
M11_ORDER = 7_920

# Classes with identical spectra in the 11-point action are aggregated.
M11_CLASS_DATA: tuple[tuple[str, int, CycleShape], ...] = (
    ("1A", 1, ((1, 11),)),
    ("2A", 165, ((1, 3), (2, 4))),
    ("3A", 440, ((1, 2), (3, 3))),
    ("4A", 990, ((1, 3), (4, 2))),
    ("5A", 1_584, ((1, 1), (5, 2))),
    ("6A", 1_320, ((2, 1), (3, 1), (6, 1))),
    ("8AB", 1_980, ((1, 1), (2, 1), (8, 1))),
    ("11AB", 1_440, ((11, 1),)),
)


def identity(size: int) -> Permutation:
    return tuple(range(size))


def permutation_from_cycles(
    size: int, cycles: Sequence[Sequence[int]]
) -> Permutation:
    """Build a zero-based permutation from one-based disjoint cycles."""

    answer = list(range(size))
    for cycle in cycles:
        zero_based = tuple(value - 1 for value in cycle)
        for source, target in zip(zero_based, zero_based[1:] + zero_based[:1]):
            answer[source] = target
    return tuple(answer)


def compose(left: Permutation, right: Permutation) -> Permutation:
    """Return left after right."""

    return tuple(left[right[index]] for index in range(len(left)))


def inverse(permutation: Permutation) -> Permutation:
    answer = [0] * len(permutation)
    for source, target in enumerate(permutation):
        answer[target] = source
    return tuple(answer)


def power(permutation: Permutation, exponent: int) -> Permutation:
    answer = identity(len(permutation))
    base = permutation
    while exponent:
        if exponent & 1:
            answer = compose(answer, base)
        base = compose(base, base)
        exponent //= 2
    return answer


def permutation_order(permutation: Permutation) -> int:
    answer = identity(len(permutation))
    current = answer
    for exponent in range(1, 10_000):
        current = compose(permutation, current)
        if current == answer:
            return exponent
    raise RuntimeError("order search exceeded its safe bound")


def word(generators: dict[str, Permutation], letters: str) -> Permutation:
    answer = identity(len(next(iter(generators.values()))))
    for letter in letters:
        answer = compose(generators[letter], answer)
    return answer


def m11_generators() -> tuple[Permutation, Permutation]:
    """ATLAS standard generators in the natural 11-point action."""

    a = permutation_from_cycles(
        11, ((2, 10), (4, 11), (5, 7), (8, 9))
    )
    b = permutation_from_cycles(
        11, ((1, 4, 3, 8), (2, 5, 6, 9))
    )
    return a, b


@lru_cache(maxsize=1)
def enumerate_m11() -> tuple[Permutation, ...]:
    generators = m11_generators()
    moves = (*generators, *(inverse(g) for g in generators))
    found = {identity(11)}
    queue = deque(found)
    while queue:
        current = queue.popleft()
        for generator in moves:
            candidate = compose(generator, current)
            if candidate not in found:
                found.add(candidate)
                queue.append(candidate)
    return tuple(sorted(found))


def cycle_shape(permutation: Permutation) -> CycleShape:
    counts: Counter[int] = Counter()
    seen: set[int] = set()
    for start in range(len(permutation)):
        if start in seen:
            continue
        current = start
        length = 0
        while current not in seen:
            seen.add(current)
            length += 1
            current = permutation[current]
        counts[length] += 1
    return tuple(sorted(counts.items()))


def permutation_matrix(permutation: Permutation) -> np.ndarray:
    """Matrix P with P e_j = e_{permutation[j]}."""

    matrix = np.zeros((len(permutation), len(permutation)), dtype=np.int64)
    for source, target in enumerate(permutation):
        matrix[target, source] = 1
    return matrix


def deleted_permutation_matrix(permutation: Permutation) -> np.ndarray:
    """Restriction to sum-zero vectors in basis e_i-e_11, 1 <= i <= 10."""

    matrix = np.zeros((10, 10), dtype=np.int64)
    anchor_image = permutation[10]
    for source in range(10):
        target = permutation[source]
        if target < 10:
            matrix[target, source] += 1
        if anchor_image < 10:
            matrix[anchor_image, source] -= 1
    return matrix


@lru_cache(maxsize=2)
def matrix_group(representation: str) -> tuple[np.ndarray, ...]:
    constructors = {
        "permutation": permutation_matrix,
        "deleted": deleted_permutation_matrix,
    }
    if representation not in constructors:
        raise ValueError(f"unknown representation: {representation}")
    constructor = constructors[representation]
    return tuple(constructor(g) for g in enumerate_m11())


def complete_coefficients_from_matrix(
    matrix: np.ndarray, maximum_degree: int
) -> tuple[int, ...]:
    """Use Newton's recurrence h_d=(1/d) sum_r tr(A^r)h_(d-r)."""

    traces = [0] * (maximum_degree + 1)
    current = np.eye(matrix.shape[0], dtype=np.int64)
    for exponent in range(1, maximum_degree + 1):
        current = current @ matrix
        traces[exponent] = int(np.trace(current))
    complete = [1]
    for degree in range(1, maximum_degree + 1):
        numerator = sum(
            traces[exponent] * complete[degree - exponent]
            for exponent in range(1, degree + 1)
        )
        assert numerator % degree == 0
        complete.append(numerator // degree)
    return tuple(complete)


def complete_coefficients_from_shape(
    shape: CycleShape, maximum_degree: int, representation: str
) -> tuple[int, ...]:
    """Expand the determinant formula using only the cycle shape."""

    coefficients = [0] * (maximum_degree + 1)
    coefficients[0] = 1
    for length, multiplicity in shape:
        updated = [0] * (maximum_degree + 1)
        for old_degree, old_value in enumerate(coefficients):
            for copies in range((maximum_degree - old_degree) // length + 1):
                updated[old_degree + copies * length] += old_value * comb(
                    multiplicity + copies - 1, copies
                )
        coefficients = updated
    if representation == "permutation":
        return tuple(coefficients)
    if representation == "deleted":
        return tuple(
            coefficients[degree] - (coefficients[degree - 1] if degree else 0)
            for degree in range(maximum_degree + 1)
        )
    raise ValueError(representation)


def complete_coefficients_from_power_character(
    shape: CycleShape, maximum_degree: int, representation: str
) -> tuple[int, ...]:
    """Expand exp(sum_r chi(g^r)t^r/r) through Newton's recurrence."""

    traces = [0] * (maximum_degree + 1)
    for exponent in range(1, maximum_degree + 1):
        traces[exponent] = sum(
            length * multiplicity
            for length, multiplicity in shape
            if exponent % length == 0
        )
        if representation == "deleted":
            traces[exponent] -= 1
        elif representation != "permutation":
            raise ValueError(representation)
    complete = [1]
    for degree in range(1, maximum_degree + 1):
        numerator = sum(
            traces[exponent] * complete[degree - exponent]
            for exponent in range(1, degree + 1)
        )
        assert numerator % degree == 0
        complete.append(numerator // degree)
    return tuple(complete)


def integer_partitions(total: int, maximum: int | None = None):
    """Yield nonincreasing positive integer partitions."""

    if total == 0:
        yield ()
        return
    if maximum is None or maximum > total:
        maximum = total
    for first in range(maximum, 0, -1):
        for tail in integer_partitions(total - first, first):
            yield (first, *tail)


def coefficient_sweep(maximum_degree: int = 6) -> tuple[dict[str, object], ...]:
    rows: list[dict[str, object]] = []
    partitions = tuple(
        partition
        for total in range(1, maximum_degree + 1)
        for partition in integer_partitions(total)
    )
    for representation in ("permutation", "deleted"):
        direct_complete = tuple(
            complete_coefficients_from_matrix(matrix, maximum_degree)
            for matrix in matrix_group(representation)
        )
        determinant_complete = tuple(
            complete_coefficients_from_shape(shape, maximum_degree, representation)
            for _, _, shape in M11_CLASS_DATA
        )
        power_complete = tuple(
            complete_coefficients_from_power_character(
                shape, maximum_degree, representation
            )
            for _, _, shape in M11_CLASS_DATA
        )
        assert determinant_complete == power_complete
        for tau in partitions:
            direct_numerator = sum(
                prod(complete[degree] for degree in tau)
                for complete in direct_complete
            )
            assert direct_numerator % M11_ORDER == 0
            direct = direct_numerator // M11_ORDER
            formula_numerator = sum(
                class_size * prod(complete[degree] for degree in tau)
                for (_, class_size, _), complete in zip(
                    M11_CLASS_DATA, determinant_complete
                )
            )
            assert formula_numerator % M11_ORDER == 0
            formula = formula_numerator // M11_ORDER
            rows.append(
                {
                    "representation": representation,
                    "tau": tau,
                    "direct matrix average": direct,
                    "class determinant": formula,
                    "class power-character": formula,
                    "passed": direct == formula,
                }
            )
    return tuple(rows)


def _apply_configuration(
    generator: Permutation, state: tuple[tuple[int, ...], ...]
) -> tuple[tuple[int, ...], ...]:
    return tuple(
        tuple(sorted(generator[index] for index in block)) for block in state
    )


def configuration_orbit_count(tau: Sequence[int]) -> int:
    """Direct generator traversal on a product of multiset bases."""

    blocks = tuple(
        tuple(combinations_with_replacement(range(11), degree)) for degree in tau
    )
    remaining = set(product(*blocks))
    generators = m11_generators()
    moves = (*generators, *(inverse(g) for g in generators))
    orbits = 0
    while remaining:
        orbits += 1
        seed = remaining.pop()
        queue = deque([seed])
        while queue:
            current = queue.popleft()
            for generator in moves:
                candidate = _apply_configuration(generator, current)
                if candidate in remaining:
                    remaining.remove(candidate)
                    queue.append(candidate)
    return orbits


def orbit_sweep() -> tuple[dict[str, object], ...]:
    coefficient_lookup = {
        (row["representation"], row["tau"]): row["class determinant"]
        for row in coefficient_sweep(4)
    }
    rows = []
    for tau in ((1,), (2,), (1, 1), (3,), (2, 1), (2, 2), (1, 1, 1, 1)):
        direct = configuration_orbit_count(tau)
        formula = coefficient_lookup[("permutation", tau)]
        rows.append(
            {
                "tau": tau,
                "generator orbits": direct,
                "class formula": formula,
                "passed": direct == formula,
            }
        )
    return tuple(rows)


def determinant_integrand(matrix: np.ndarray, variables: Sequence[float]) -> float:
    identity_matrix = np.eye(matrix.shape[0])
    return prod(
        1.0 / np.linalg.det(identity_matrix - variable * matrix)
        for variable in variables
    )


def shape_integrand(
    shape: CycleShape, variables: Sequence[float], representation: str
) -> float:
    value = prod(
        (1.0 - variable**length) ** (-multiplicity)
        for variable in variables
        for length, multiplicity in shape
    )
    if representation == "deleted":
        value *= prod(1.0 - variable for variable in variables)
    elif representation != "permutation":
        raise ValueError(representation)
    return value


def numerical_sweep(
    variables: Sequence[float] = (0.037, -0.051, 0.083)
) -> tuple[dict[str, object], ...]:
    rows = []
    for representation in ("permutation", "deleted"):
        direct = sum(
            determinant_integrand(matrix, variables)
            for matrix in matrix_group(representation)
        ) / M11_ORDER
        formula = sum(
            class_size * shape_integrand(shape, variables, representation)
            for _, class_size, shape in M11_CLASS_DATA
        ) / M11_ORDER
        error = abs(direct - formula)
        rows.append(
            {
                "representation": representation,
                "variables": tuple(variables),
                "direct determinant average": direct,
                "class formula": formula,
                "absolute error": error,
                "passed": error < 5e-13,
            }
        )
    return tuple(rows)


def representation_checks() -> dict[str, object]:
    a, b = m11_generators()
    elements = enumerate_m11()
    observed_shapes = Counter(cycle_shape(g) for g in elements)
    expected_shapes = Counter(
        {shape: class_size for _, class_size, shape in M11_CLASS_DATA}
    )
    permutation_matrices = matrix_group("permutation")
    deleted_matrices = matrix_group("deleted")

    indices = ((0, 1), (17, 711), (306, 7_001), (4_200, 87))
    locations = {element: index for index, element in enumerate(elements)}
    homomorphism_checks = 0
    for left_index, right_index in indices:
        product_index = locations[compose(elements[left_index], elements[right_index])]
        for matrices in (permutation_matrices, deleted_matrices):
            assert np.array_equal(
                matrices[left_index] @ matrices[right_index], matrices[product_index]
            )
            homomorphism_checks += 1

    generator_dict = {"a": a, "b": b}
    fingerprint = {
        "o(a)": permutation_order(a),
        "o(b)": permutation_order(b),
        "o(ab)": permutation_order(compose(a, b)),
        "o(ababbabbb)": permutation_order(word(generator_dict, "ababbabbb")),
    }
    passed = (
        len(elements) == M11_ORDER
        and observed_shapes == expected_shapes
        and fingerprint == {
            "o(a)": 2,
            "o(b)": 4,
            "o(ab)": 11,
            "o(ababbabbb)": 5,
        }
        and len({matrix.tobytes() for matrix in permutation_matrices}) == M11_ORDER
        and len({matrix.tobytes() for matrix in deleted_matrices}) == M11_ORDER
    )
    return {
        "group order": len(elements),
        "dimensions": (11, 10),
        "aggregated spectra": len(observed_shapes),
        "fingerprint": fingerprint,
        "homomorphism checks": homomorphism_checks,
        "passed": passed,
    }


@lru_cache(maxsize=1)
def run_suite(maximum_degree: int = 6) -> dict[str, object]:
    representation = representation_checks()
    coefficients = coefficient_sweep(maximum_degree)
    orbits = orbit_sweep()
    numerical = numerical_sweep()
    passed = (
        representation["passed"]
        and all(row["passed"] for row in coefficients)
        and all(row["passed"] for row in orbits)
        and all(row["passed"] for row in numerical)
    )
    return {
        "representation": representation,
        "coefficients": coefficients,
        "orbits": orbits,
        "numerical": numerical,
        "maximum degree": maximum_degree,
        "exact coefficient checks": len(coefficients),
        "passed": passed,
    }


if __name__ == "__main__":
    result = run_suite()
    print(f"M11 order: {result['representation']['group order']}")
    print(f"coefficient comparisons: {result['exact coefficient checks']}")
    print(f"result: {'PASS' if result['passed'] else 'FAIL'}")
    for row in result["numerical"]:
        print(row)

