"""Explicit small Barnes--Wall, real Clifford, and real Pauli groups.

The routines deliberately use matrix closure rather than character tables.
They are intended for discriminating low-rank checks, not large-rank group
enumeration.
"""

from __future__ import annotations

from collections import deque
from itertools import product
from math import comb

import numpy as np


TOL = 3.0e-7


def matrix_key(matrix: np.ndarray) -> tuple[float, ...]:
    """A stable key for the dyadic orthogonal matrices used here."""
    candidate = np.asarray(matrix, dtype=np.complex128).copy()
    candidate.real[np.abs(candidate.real) < 1.0e-10] = 0.0
    candidate.imag[np.abs(candidate.imag) < 1.0e-10] = 0.0
    return tuple(np.round(candidate.real, 10).flat) + tuple(
        np.round(candidate.imag, 10).flat
    )


def close_matrix_group(generators: list[np.ndarray], limit: int) -> list[np.ndarray]:
    """Return the group generated by ``generators`` by breadth-first closure."""
    dimension = generators[0].shape[0]
    identity = np.eye(dimension, dtype=np.complex128)
    seen = {matrix_key(identity): identity}
    frontier = deque([identity])
    while frontier:
        current = frontier.popleft()
        for generator in generators:
            candidate = current @ generator
            key = matrix_key(candidate)
            if key not in seen:
                seen[key] = candidate
                frontier.append(candidate)
        if len(seen) > limit:
            raise RuntimeError(f"matrix closure exceeded the safety limit {limit}")
    return list(seen.values())


def tensor_placement(matrix: np.ndarray, site: int, qubits: int) -> np.ndarray:
    result = np.array([[1.0]], dtype=np.complex128)
    identity = np.eye(2, dtype=np.complex128)
    for index in range(qubits):
        result = np.kron(result, matrix if index == site else identity)
    return result


def real_pauli_group(m: int) -> list[np.ndarray]:
    """The plus-type extraspecial group ``E_m = {+- X^a Z^b}``."""
    if m < 1:
        raise ValueError("m must be positive")
    identity = np.eye(2, dtype=np.complex128)
    x = np.array([[0, 1], [1, 0]], dtype=np.complex128)
    z = np.diag([1.0, -1.0]).astype(np.complex128)
    local = {(0, 0): identity, (1, 0): x, (0, 1): z, (1, 1): x @ z}
    matrices: list[np.ndarray] = []
    for sign in (1.0, -1.0):
        for labels in product(local, repeat=m):
            matrix = np.array([[sign]], dtype=np.complex128)
            for label in labels:
                matrix = np.kron(matrix, local[label])
            matrices.append(matrix)
    assert len({matrix_key(matrix) for matrix in matrices}) == 2 ** (1 + 2 * m)
    return matrices


def cnot_matrix(control: int, target: int, qubits: int) -> np.ndarray:
    dimension = 2**qubits
    matrix = np.zeros((dimension, dimension), dtype=np.complex128)
    for column in range(dimension):
        bits = [(column >> (qubits - 1 - j)) & 1 for j in range(qubits)]
        if bits[control]:
            bits[target] ^= 1
        row = sum(bit << (qubits - 1 - j) for j, bit in enumerate(bits))
        matrix[row, column] = 1.0
    return matrix


def cz_matrix(first: int, second: int, qubits: int) -> np.ndarray:
    diagonal = []
    for column in range(2**qubits):
        bits = [(column >> (qubits - 1 - j)) & 1 for j in range(qubits)]
        diagonal.append(-1.0 if bits[first] and bits[second] else 1.0)
    return np.diag(diagonal).astype(np.complex128)


def real_clifford_group(m: int) -> list[np.ndarray]:
    """Close ``C_m=N_O(E_m)`` for the explicit ranks m=1,2."""
    if m not in (1, 2):
        raise ValueError("explicit Clifford closure is intentionally limited to m=1,2")
    x = np.array([[0, 1], [1, 0]], dtype=np.complex128)
    z = np.diag([1.0, -1.0]).astype(np.complex128)
    h = np.array([[1, 1], [1, -1]], dtype=np.complex128) / np.sqrt(2.0)
    dimension = 2**m
    generators = [-np.eye(dimension, dtype=np.complex128)]
    for site in range(m):
        generators.extend(
            [tensor_placement(x, site, m), tensor_placement(z, site, m)]
        )
        generators.append(tensor_placement(h, site, m))
    if m == 2:
        generators.append(cnot_matrix(0, 1, 2))
    expected = {1: 16, 2: 2304}[m]
    matrices = close_matrix_group(generators, limit=expected)
    assert len(matrices) == expected
    return matrices


def barnes_wall_group(m: int) -> list[np.ndarray]:
    """Return Aut(BW_2) and Aut(BW_4) in the standard Z^2/D4 models."""
    if m == 1:
        return real_pauli_group(1)
    if m != 2:
        raise ValueError("explicit Barnes--Wall closure is limited to m=1,2")
    x = np.array([[0, 1], [1, 0]], dtype=np.complex128)
    z = np.diag([1.0, -1.0]).astype(np.complex128)
    h = np.array([[1, 1], [1, -1]], dtype=np.complex128) / np.sqrt(2.0)
    generators = [
        -np.eye(4, dtype=np.complex128),
        tensor_placement(x, 0, 2),
        tensor_placement(z, 0, 2),
        tensor_placement(x, 1, 2),
        tensor_placement(z, 1, 2),
        np.kron(h, h),
        cnot_matrix(0, 1, 2),
        cz_matrix(0, 1, 2),
    ]
    matrices = close_matrix_group(generators, limit=1152)
    assert len(matrices) == 1152
    return matrices


def complete_homogeneous(eigenvalues: np.ndarray, degree: int) -> complex:
    coefficients = np.zeros(degree + 1, dtype=np.complex128)
    coefficients[0] = 1.0
    for value in eigenvalues:
        updated = coefficients.copy()
        for current_degree in range(1, degree + 1):
            updated[current_degree] = (
                coefficients[current_degree] + value * updated[current_degree - 1]
            )
        coefficients = updated
    return complex(coefficients[degree])


def symmetric_character(matrix: np.ndarray, degree: int) -> complex:
    return complete_homogeneous(np.linalg.eigvals(matrix), degree)


def coefficient_integrand(matrix: np.ndarray, tau: tuple[int, ...]) -> complex:
    eigenvalues = np.linalg.eigvals(matrix)
    maximum = max(tau, default=0)
    h = [complete_homogeneous(eigenvalues, degree) for degree in range(maximum + 1)]
    return complex(np.prod([h[degree] for degree in tau]))


def target_coefficient(
    matrices: list[np.ndarray], tau: tuple[int, ...], weights: list[int] | None = None
) -> complex:
    if weights is None:
        weights = [1] * len(matrices)
    return sum(
        weight * coefficient_integrand(matrix, tau)
        for matrix, weight in zip(matrices, weights, strict=True)
    ) / len(matrices)


def clean_integer(value: complex, tolerance: float = TOL) -> int:
    rounded = int(round(value.real))
    if abs(value.imag) > tolerance or abs(value.real - rounded) > tolerance:
        raise AssertionError(f"expected an integer, received {value!r}")
    return rounded


def assert_real_orthogonal_representation(matrices: list[np.ndarray]) -> None:
    """Check the defining real orthogonal representation matrix by matrix."""
    if not matrices:
        raise AssertionError("the representation contains no matrices")
    dimension = matrices[0].shape[0]
    identity = np.eye(dimension, dtype=np.complex128)
    for matrix in matrices:
        if matrix.shape != (dimension, dimension):
            raise AssertionError("inconsistent representation dimensions")
        if np.max(np.abs(matrix.imag)) >= TOL:
            raise AssertionError("the purported real representation is not real")
        if not np.allclose(matrix.conj().T @ matrix, identity, atol=TOL):
            raise AssertionError("the purported representation is not orthogonal")


def extraspecial_formula_coefficient(m: int, tau: tuple[int, ...]) -> int:
    """Coefficient of the four-term formula (11.5)."""
    dimension = 2**m
    if sum(tau) % 2:
        return 0
    central_term = 1
    for degree in tau:
        central_term *= comb(dimension + degree - 1, degree)
    numerator = 2 * central_term

    if all(degree % 2 == 0 for degree in tau):
        half_term = 1
        for degree in tau:
            half_term *= comb(dimension // 2 + degree // 2 - 1, degree // 2)
        involution_count = dimension**2 + dimension - 2
        order_four_count = dimension**2 - dimension
        numerator += half_term * (
            involution_count
            + ((-1) ** (sum(tau) // 2)) * order_four_count
        )
    result, remainder = divmod(numerator, 2 * dimension**2)
    if remainder:
        raise AssertionError("formula coefficient unexpectedly failed integrality")
    return result


def coset_representatives(
    group: list[np.ndarray], subgroup: list[np.ndarray]
) -> list[np.ndarray]:
    """Partition ``group`` into right cosets ``subgroup * representative``."""
    group_by_key = {matrix_key(matrix): matrix for matrix in group}
    remaining = set(group_by_key)
    representatives: list[np.ndarray] = []
    while remaining:
        representative = group_by_key[next(iter(remaining))]
        representatives.append(representative)
        coset = {matrix_key(element @ representative) for element in subgroup}
        if not coset <= set(group_by_key):
            raise AssertionError("subgroup coset escaped the ambient group")
        remaining.difference_update(coset)
    assert len(representatives) * len(subgroup) == len(group)
    return representatives


def coset_average_coefficient(
    subgroup: list[np.ndarray], representatives: list[np.ndarray], tau: tuple[int, ...]
) -> complex:
    coset_means = coset_coefficient_means(subgroup, representatives, tau)
    return sum(coset_means) / len(coset_means)


def coset_coefficient_means(
    subgroup: list[np.ndarray], representatives: list[np.ndarray], tau: tuple[int, ...]
) -> list[complex]:
    """Return the coefficient contribution of each individual right coset."""
    coset_means: list[complex] = []
    for representative in representatives:
        coset_means.append(
            sum(
                coefficient_integrand(element @ representative, tau)
                for element in subgroup
            )
            / len(subgroup)
        )
    return coset_means


def barnes_wall_lattice_basis(m: int) -> np.ndarray:
    if m == 1:
        return np.eye(2, dtype=np.complex128)
    if m == 2:
        # Columns generate D4 = {x in Z^4 : sum x_i is even}.
        return np.array(
            [[1, 0, 0, 0], [-1, 1, 0, 0], [0, -1, 1, 1], [0, 0, -1, 1]],
            dtype=np.complex128,
        )
    raise ValueError("lattice basis is supplied only for m=1,2")


def preserves_lattice(matrix: np.ndarray, basis: np.ndarray) -> bool:
    coordinates = np.linalg.solve(basis, matrix @ basis)
    rounded = np.round(coordinates.real)
    return bool(
        np.max(np.abs(coordinates.imag)) < TOL
        and np.max(np.abs(coordinates.real - rounded)) < TOL
        and abs(round(np.linalg.det(coordinates).real)) == 1
    )
